[[plugins]]
repo = 'Shougo/ddc.vim'

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'Shougo/pum.vim'

[[plugins]]
repo = 'Shougo/ddc-around'

[[plugins]]
repo = 'LumaKernel/ddc-file'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'

[[plugins]]
repo = 'Shougo/ddc-converter_remove_overlap'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'hrsh7th/vim-vsnip'

[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'

[[plugins]]
repo = 'neovim/nvim-lspconfig'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'lambdalisue/gina.vim'
hook_add = '''
  nmap <leader>gs <cmd>Gina status<cr>
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
[[plugins]]
repo =  'vim-airline/vim-airline-themes'
[[plugins]]
repo =  'tpope/vim-commentary'
[[plugins]]
repo = 'preservim/nerdtree'
[[plugins]]
repo = 'ryanoasis/vim-devicons'
 
[[plugins]]
repo = 'preservim/nerdtree'
