[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'lambdalisue/gina.vim'
hook_add = '''
  nmap <leader>gs <cmd>Gina status<cr>
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
[[plugins]]
repo =  'vim-airline/vim-airline-themes'
[[plugins]]
repo = 'ryanoasis/vim-devicons'
 
[[plugins]]
repo = 'preservim/nerdtree'

[[plugins]]
repo = 'rhysd/vim-operator-user'

[[plugins]]
repo = 'rhysd/vim-clang-format'

